import { useState, useEffect, createContext, useContext } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    home: "Home",
    services: "Services",
    about: "About",
    contact: "Contact",
    login: "Login",
    quickLinks: "Quick Links",
    discover: "Discover",
    heroTitle: "Crafting Elegance for Your Space",
    heroSubtitle: "Premium quality furniture with timeless design and masterful craftsmanship.",
    exploreCollection: "Explore Our Services",
    contactUs: "Contact Us",
    ourServices: "Our Services",
    servicesDesc: "Click a category to explore our furniture collections.",
    office: "Office",
    officeDesc: "Professional office and workspace furniture crafted for productivity.",
    kitchen: "Kitchen",
    kitchenDesc: "Modern and functional kitchen furniture for culinary spaces.",
    bedroom: "Bedroom",
    bedroomDesc: "Elegant bedroom furniture for your personal sanctuary.",
    aboutUs: "About SARL AK",
    aboutText1: "SARL AK — Algerienne Lil Maktabia — is a leading furniture manufacturer based in Bordj Bou Arréridj, Algeria.",
    aboutText2: "We combine traditional craftsmanship with modern design to create durable, elegant furniture. Every piece reflects our commitment to quality, sustainability, and beauty.",
    whyChooseUs: "Why Choose Us",
    quality: "Premium Quality",
    qualityDesc: "Made from the finest materials.",
    craftsmanship: "Master Craftsmanship",
    craftsmanshipDesc: "Decades of woodworking expertise.",
    design: "Timeless Design",
    designDesc: "Aesthetics that never go out of style.",
    local: "Premium Quality",
    localDesc: "Every piece is built to last — superior materials, exceptional finish, and timeless character.",
    getInTouch: "Get In Touch",
    name: "Full Name",
    email: "Email Address",
    phone: "Phone Number",
    message: "Your Message",
    sendMessage: "Send Message",
    sending: "Sending...",
    messageSent: "Message sent successfully!",
    messageError: "Failed to send message. Please try again.",
    rights: "All rights reserved.",
    backHome: "Back to Home",
    productsTitle: "Our Products",
    noProducts: "No products yet. Check back soon.",
    loadMore: "Load More",
    contactWhatsApp: "Contact via WhatsApp",
    addToCart: "Add to Cart",
    viewDetails: "View Details",
    cart: "Cart",
    cartEmpty: "Your cart is empty",
    cartEmptyDesc: "Browse our products and add items to your cart.",
    remove: "Remove",
    quantity: "Qty",
    total: "Total",
    subtotal: "Subtotal",
    placeOrder: "Place Order",
    orderName: "Full Name",
    orderPhone: "Phone Number",
    orderEmail: "Email (optional)",
    orderSuccess: "Order placed successfully! We will contact you soon.",
    orderError: "Failed to place order. Please try again.",
    placingOrder: "Placing order...",
    dzd: "DZD",
    priceOnRequest: "Price on request",
    close: "Close",
    orderSummary: "Order Summary",
    confirmOrder: "Confirm Order",
    customerInfo: "Your Information",
    backToCart: "Back to Cart",
    addedToCart: "Added to cart",
    ourLocations: "Our Locations",
    locationBBA: "Bordj Bou Arréridj",
    locationAlgiers: "Algiers",
    openInMaps: "Open in Maps",
  },
  fr: {
    home: "Accueil",
    services: "Services",
    about: "À Propos",
    contact: "Contact",
    login: "Connexion",
    quickLinks: "Liens Rapides",
    discover: "Découvrir",
    heroTitle: "L'Élégance pour Votre Espace",
    heroSubtitle: "Des meubles de qualité supérieure avec un design intemporel et un savoir-faire magistral.",
    exploreCollection: "Voir nos Services",
    contactUs: "Contactez-nous",
    ourServices: "Nos Services",
    servicesDesc: "Cliquez sur une catégorie pour explorer nos collections de meubles.",
    office: "Bureau",
    officeDesc: "Mobilier de bureau professionnel conçu pour la productivité.",
    kitchen: "Cuisine",
    kitchenDesc: "Mobilier de cuisine moderne et fonctionnel.",
    bedroom: "Chambre",
    bedroomDesc: "Mobilier de chambre élégant pour votre espace personnel.",
    aboutUs: "À Propos de SARL AK",
    aboutText1: "SARL AK — Algerienne Lil Maktabia — est un fabricant de meubles de premier plan basé à Bordj Bou Arréridj, Algérie.",
    aboutText2: "Nous combinons l'artisanat traditionnel avec le design moderne pour créer des meubles durables et élégants.",
    whyChooseUs: "Pourquoi Nous Choisir",
    quality: "Qualité Supérieure",
    qualityDesc: "Fabriqué avec les meilleurs matériaux.",
    craftsmanship: "Savoir-faire",
    craftsmanshipDesc: "Des décennies d'expertise.",
    design: "Design Intemporel",
    designDesc: "Une esthétique toujours élégante.",
    local: "Qualité Premium",
    localDesc: "Chaque meuble est conçu pour durer — matériaux supérieurs, finition irréprochable et caractère intemporel.",
    getInTouch: "Contactez-nous",
    name: "Nom Complet",
    email: "Adresse Email",
    phone: "Numéro de Téléphone",
    message: "Votre Message",
    sendMessage: "Envoyer",
    sending: "Envoi en cours...",
    messageSent: "Message envoyé avec succès !",
    messageError: "Échec de l'envoi. Veuillez réessayer.",
    rights: "Tous droits réservés.",
    backHome: "Retour à l'accueil",
    productsTitle: "Nos Produits",
    noProducts: "Aucun produit pour l'instant.",
    loadMore: "Charger plus",
    contactWhatsApp: "Contacter via WhatsApp",
    addToCart: "Ajouter au panier",
    viewDetails: "Voir les détails",
    cart: "Panier",
    cartEmpty: "Votre panier est vide",
    cartEmptyDesc: "Parcourez nos produits et ajoutez des articles à votre panier.",
    remove: "Supprimer",
    quantity: "Qté",
    total: "Total",
    subtotal: "Sous-total",
    placeOrder: "Passer la commande",
    orderName: "Nom Complet",
    orderPhone: "Numéro de Téléphone",
    orderEmail: "Email (optionnel)",
    orderSuccess: "Commande passée avec succès ! Nous vous contacterons bientôt.",
    orderError: "Échec de la commande. Veuillez réessayer.",
    placingOrder: "En cours...",
    dzd: "DZD",
    priceOnRequest: "Prix sur demande",
    close: "Fermer",
    orderSummary: "Récapitulatif de commande",
    confirmOrder: "Confirmer la commande",
    customerInfo: "Vos coordonnées",
    backToCart: "Retour au panier",
    addedToCart: "Ajouté au panier",
    ourLocations: "Nos Emplacements",
    locationBBA: "Bordj Bou Arréridj",
    locationAlgiers: "Alger",
    openInMaps: "Ouvrir dans Maps",
  },
  ar: {
    home: "الرئيسية",
    services: "الخدمات",
    about: "من نحن",
    contact: "اتصل بنا",
    login: "دخول",
    quickLinks: "روابط سريعة",
    discover: "اكتشف",
    heroTitle: "نصنع الأناقة لمساحتك",
    heroSubtitle: "أثاث عالي الجودة بتصميم خالد وبراعة فنية راقية.",
    exploreCollection: "استكشف خدماتنا",
    contactUs: "اتصل بنا",
    ourServices: "خدماتنا",
    servicesDesc: "اضغط على فئة لاستعراض مجموعاتنا من الأثاث.",
    office: "بيرو",
    officeDesc: "أثاث مكتبي احترافي مصمم لزيادة الإنتاجية.",
    kitchen: "مطبخ",
    kitchenDesc: "أثاث مطبخ عصري وعملي للمساحات الطبخية.",
    bedroom: "غرفة نوم",
    bedroomDesc: "أثاث غرفة نوم أنيق لملاذك الشخصي.",
    aboutUs: "نبذة عن SARL AK",
    aboutText1: "شركة SARL AK — الجزائرية للمكتبية — هي شركة رائدة في صناعة الأثاث، مقرها ولاية برج بوعريريج، الجزائر.",
    aboutText2: "نجمع بين الحرفية التقليدية والتصميم الحديث لإنشاء أثاث متين وأنيق. كل قطعة تعكس التزامنا بالجودة والجمال.",
    whyChooseUs: "لماذا تختارنا",
    quality: "جودة عالية",
    qualityDesc: "مصنوع من أفضل المواد.",
    craftsmanship: "براعة فنية",
    craftsmanshipDesc: "عقود من الخبرة في النجارة.",
    design: "تصميم خالد",
    designDesc: "جماليات راقية لا تتقادم.",
    local: "جودة متميزة",
    localDesc: "كل قطعة مصممة لتدوم — مواد راقية، تشطيب استثنائي، وطابع خالد لا يتقادم.",
    getInTouch: "تواصل معنا",
    name: "الاسم الكامل",
    email: "البريد الإلكتروني",
    phone: "رقم الهاتف",
    message: "رسالتك",
    sendMessage: "إرسال الرسالة",
    sending: "جاري الإرسال...",
    messageSent: "تم إرسال الرسالة بنجاح!",
    messageError: "فشل إرسال الرسالة. يرجى المحاولة مرة أخرى.",
    rights: "جميع الحقوق محفوظة.",
    backHome: "العودة إلى الرئيسية",
    productsTitle: "منتجاتنا",
    noProducts: "لا توجد منتجات حالياً.",
    loadMore: "تحميل المزيد",
    contactWhatsApp: "تواصل عبر واتساب",
    addToCart: "أضف إلى السلة",
    viewDetails: "عرض التفاصيل",
    cart: "السلة",
    cartEmpty: "سلتك فارغة",
    cartEmptyDesc: "تصفح منتجاتنا وأضف العناصر إلى سلتك.",
    remove: "حذف",
    quantity: "الكمية",
    total: "الإجمالي",
    subtotal: "المجموع",
    placeOrder: "تأكيد الطلب",
    orderName: "الاسم الكامل",
    orderPhone: "رقم الهاتف",
    orderEmail: "البريد الإلكتروني (اختياري)",
    orderSuccess: "تم تقديم طلبك بنجاح! سنتواصل معك قريباً.",
    orderError: "فشل تقديم الطلب. يرجى المحاولة مرة أخرى.",
    placingOrder: "جاري التقديم...",
    dzd: "دج",
    priceOnRequest: "السعر عند الطلب",
    close: "إغلاق",
    orderSummary: "ملخص الطلب",
    confirmOrder: "تأكيد الطلب",
    customerInfo: "معلوماتك الشخصية",
    backToCart: "العودة إلى السلة",
    addedToCart: "تمت الإضافة إلى السلة",
    ourLocations: "مواقعنا",
    locationBBA: "برج بوعريريج",
    locationAlgiers: "الجزائر العاصمة",
    openInMaps: "فتح في الخريطة",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('sarl-ak-lang');
    return (saved as Language) || 'ar';
  });

  useEffect(() => {
    localStorage.setItem('sarl-ak-lang', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
